services:
  api:
    build: .
    ports:
      - "5000:8000"
    environment:
      FLASK_ENV: development
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
