version = 0.1

[default.deploy.parameters]
stack_name = "undocs-undl-api"
resolve_s3 = true
s3_prefix = "undocs-undl-api"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FlaskEnv=\"production\" ProvisionedConcurrentExecutions=\"1\""
tags = "Project=\"undocs-undl-api\" Environment=\"production\""
image_repositories = ["UndlApiFunction=950236537949.dkr.ecr.us-east-1.amazonaws.com/undocsundlapi588d5106/undlapifunction60d4ba24repo"]

[default.build.parameters]
use_container = true


[default.global.parameters]
region = "us-east-1"
[dev.deploy.parameters]
stack_name = "undocs-undl-api"
resolve_s3 = true
s3_prefix = "undocs-undl-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FlaskEnv=\"development\" ProvisionedConcurrentExecutions=\"1\""
tags = "Project=\"undocs-undl-api\" Environment=\"development\""
resolve_image_repos = true
fail_on_empty_changeset = false



[dev.global.parameters]
region = "us-east-1"
[prod.deploy.parameters]
stack_name = "undocs-undl-api-prod"
resolve_s3 = true
s3_prefix = "undocs-undl-api-prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FlaskEnv=production ProvisionedConcurrentExecutions=1"
tags = "Project=\"undocs-undl-api\" Environment=\"production\""
resolve_image_repos = true
fail_on_empty_changeset = false