version = 0.1

[default.deploy.parameters]
stack_name = "undocs-undl-api"
resolve_s3 = true
s3_prefix = "undocs-undl-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FlaskEnv=production ProvisionedConcurrentExecutions=0"
image_repositories = []

[default.build.parameters]
use_container = true

[dev.deploy.parameters]
stack_name = "undocs-undl-api-dev"
resolve_s3 = true
s3_prefix = "undocs-undl-api-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FlaskEnv=development ProvisionedConcurrentExecutions=0"
resolve_image_repos = true
fail_on_empty_changeset = false

[prod.deploy.parameters]
stack_name = "undocs-undl-api-prod"
resolve_s3 = true
s3_prefix = "undocs-undl-api-prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "FlaskEnv=production ProvisionedConcurrentExecutions=0"
resolve_image_repos = true
fail_on_empty_changeset = false